# Tensorflow

In [ ]:
! pip install tensorflow

In [ ]:
import tensorflow as tf
import numpy as np
a = tf.constant([
    [1,1],
    [2,2]])
b = tf.constant([
    [3,4],
    [5,6]])
print(a+b)

tf.Tensor(
[[4 5]
 [7 8]], shape=(2, 2), dtype=int32)


In [ ]:
x = np.random.rand(100).astype(np.float32)
print(x)

[0.828404   0.43520886 0.9655252  0.37992227 0.23592047 0.6062418
 0.35505491 0.52088696 0.5118231  0.63043433 0.26129508 0.8923276
 0.65444636 0.8166529  0.10077205 0.27601144 0.5408464  0.04036139
 0.20687155 0.8434368  0.47807255 0.9696145  0.39974013 0.60994864
 0.9222119  0.7073823  0.11756299 0.6700273  0.1675228  0.212965
 0.65325177 0.06992619 0.16874373 0.83057696 0.57065165 0.22746399
 0.29203784 0.42632458 0.21078014 0.20667695 0.71418464 0.00107368
 0.4464791  0.5636476  0.5114386  0.69703    0.37476686 0.5174612
 0.55586964 0.8700233  0.34653503 0.6055182  0.95388865 0.536302
 0.38672262 0.3038079  0.23730573 0.5160766  0.5578905  0.77507967
 0.8529503  0.26936495 0.7893459  0.8710855  0.36796468 0.1152191
 0.4398605  0.397999   0.3895188  0.7352865  0.2724513  0.2637433
 0.37424716 0.3510638  0.23588316 0.0444014  0.97796184 0.5072077
 0.93016356 0.54734397 0.9583738  0.6366476  0.3483662  0.94549936
 0.47113174 0.4732402  0.36972922 0.51033473 0.04943128 0.51161635
 0.89

In [ ]:
y = x*0.2+0.2

In [ ]:
W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.zeros([1]))

In [ ]:
def mse_loss():
  ypred = W*x + b
  loss = tf.reduce_mean(tf.square(ypred-y))
  return loss

In [ ]:
optimizer = tf.optimizers.Adam()

In [ ]:
for step in range(5000):
  optimizer.minimize(mse_loss, var_list=[W,b])
  if step % 500 == 0:
    print(step, W.numpy(), b.numpy())

0 [0.8439305] [-0.00099998]
500 [0.5459576] [0.01832157]
1000 [0.335529] [0.12899819]
1500 [0.23466745] [0.18184534]
2000 [0.20521183] [0.19727074]
2500 [0.20040087] [0.19979009]
3000 [0.20001306] [0.1999932]
3500 [0.20000084] [0.19999956]
4000 [0.20000064] [0.19999966]
4500 [0.20000048] [0.19999975]


# Keras

In [ ]:
#rom tensorflow import keras
from tensorflow.keras.models import  Sequential
from tensorflow.keras.layers import Dense
import pandas as pd

In [ ]:
dataset = pd.read_csv("/content/diabetes.csv", delimiter = ",")
dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
x = dataset.iloc[:, 0:8]
print(type(x))
print(x.shape)
y = dataset.iloc[:, 8]
print(y)

<class 'pandas.core.frame.DataFrame'>
(768, 8)
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


In [ ]:
model = Sequential()
model.add(Dense(12, input_shape= (8,), activation = 'relu'))
model.add(Dense(8, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 12)                108       
                                                                 
 dense_1 (Dense)             (None, 8)                 104       
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 221 (884.00 Byte)
Trainable params: 221 (884.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x,y, epochs=150, batch_size=10)

Epoch 1/150
77/77 [==============================] - 2s 2ms/step - loss: 2.0351 - accuracy: 0.5104
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8846 - accuracy: 0.5729
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7691 - accuracy: 0.6224
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7141 - accuracy: 0.6445
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6783 - accuracy: 0.6562
Epoch 6/150
77/77 [==============================] - 0s 3ms/step - loss: 0.6493 - accuracy: 0.6576
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6367 - accuracy: 0.6510
Epoch 8/150
77/77 [==============================] - 0s 3ms/step - loss: 0.6182 - accuracy: 0.6680
Epoch 9/150
77/77 [==============================] - 0s 4ms/step - loss: 0.6079 - accuracy: 0.6667
Epoch 10/150
77/77 [==============================] - 0s 4ms/step - loss: 0.5996 - accuracy: 0.6536
Epoch 11/

In [ ]:
model.evaluate(x,y)

24/24 [==============================] - 0s 4ms/step - loss: 0.5227 - accuracy: 0.7266


[0.5227261185646057, 0.7265625]

# PyTorch

In [ ]:
import torch
import numpy as np

In [ ]:
data = [
    [1,1],
    [2,2]]

In [ ]:
x_data = torch.tensor(data)
print(type(x_data))
print(x_data)

<class 'torch.Tensor'>
tensor([[1, 1],
        [2, 2]])


In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(type(x_np))
print(x_np)

<class 'torch.Tensor'>
tensor([[1, 1],
        [2, 2]])


In [ ]:
x_random = torch.rand_like(x_data, dtype=torch.float)
print(type(x_random))
print(x_random)

<class 'torch.Tensor'>
tensor([[0.5877, 0.3290],
        [0.0726, 0.0315]])


In [ ]:
x_ones = torch.ones_like(x_data)
print(type(x_ones))
print(x_ones)

<class 'torch.Tensor'>
tensor([[1, 1],
        [1, 1]])


In [ ]:
shape = (2,3)

In [ ]:
random_tensor = torch.rand(shape)
print(random_tensor)

tensor([[0.0756, 0.1017, 0.2153],
        [0.4153, 0.3218, 0.2282]])


In [ ]:
ones_tensor = torch.ones(shape)
print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
tensor = torch.rand(3,4)
print(tensor)
print(tensor.shape)
print(tensor.device)

tensor([[0.6359, 0.8428, 0.6431, 0.3785],
        [0.1487, 0.3729, 0.3457, 0.4288],
        [0.5017, 0.3359, 0.0555, 0.0053]])
torch.Size([3, 4])
cpu


In [ ]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print("Device Tensor stored in: ", tensor.device)

In [ ]:
tensor = torch.ones(4,4)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
tensor1 = torch.zeros(4,4)
print(tensor1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
tensor2 = torch.cat([tensor, tensor1])
print(tensor2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
print(tensor.mul(tensor1))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
print(tensor.T)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
print(tensor.add_(3))

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [ ]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
print(type(n))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
